/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    BannerComponent: typeof import('./src/components/BannerComponent.vue')['default']
    CardOportunities: typeof import('./src/components/CardOportunities.vue')['default']
    CarouselOportunities: typeof import('./src/components/CarouselOportunities.vue')['default']
    CustomTab: typeof import('./src/components/CustomTab.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LisComponent: typeof import('./src/components/LisComponent.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    PercentComponent: typeof import('./src/components/PercentComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarComponent: typeof import('./src/components/SideBarComponent.vue')['default']
    VideoComponent: typeof import('./src/components/VideoComponent.vue')['default']
  }
}
